# Generated by Django 4.1.1 on 2022-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('emailid', models.EmailField(default=True, max_length=254)),
            ],
            options={
                'db_table': 'studentdetail',
            },
        ),
    ]
